### ISSUE TITLE
Roadmap for 0.1.0 release 🥇 

### ISSUE THREAD

**Issue by shenyangHuang** [shenyangHuang/openDG#9]
### TG Data Structure Implementation  
  - #2 
  - [ ] implement base TG structure that supports chronological operations efficiently
  - [ ] implement `CTDG` and `DTDG`
  - [ ] implement `aggregate_graph()` to slice the graph
  - [ ] implement type conversion `to_events()`
  - [ ] implement type conversion `to_snapshots()`, support time granularity
  - [ ] implement basic temporal graph statistics `num_edges`. `num_nodes`, `num_timestamps`
  - [ ] output to ML ready format, edge index, node feature etc. 
  - [ ] support batch data loading for events,  list of snapshots for snapshots
  
### Temporal Neighbor Sampler Implementation
  - #1 
  - [ ] implement temporal neighbor sampling data structure that supports node level queries efficiently
  - [ ] implement `uniform_sampling`, `weight_decayed_sampling`, `recency_sampling`

### Support Existing Datasets
   - [ ] provide native support for TGB datasets
   - [ ] provide native support for TGX datasets

### Reproduce TG model 
  - [ ] reproduce TGN model on TGB dataset
